name: agrobloc
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  

dependencies:
  flutter: 
    sdk: flutter

  # ðŸ“ Localisation GPS + Adresse
  geolocator: ^14.0.1
  geocoding: ^3.0.0
  web_socket_channel: ^3.0.2

  # ðŸ”‘ Auth
  jwt_decode: ^0.3.1

  # ðŸ”” Notifications
  flutter_local_notifications: ^19.4.0
  permission_handler: ^12.0.1

  # ðŸŒ RÃ©seau & autres
  cupertino_icons: ^1.0.2
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins/Poppins-Regular.ttf
        - asset: assets/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
